---
title: "Predicting TTC Subway Delay Lengths"
author: "Nevin Tsui"
date: "25 April 2026"

format:
 html:
  embed-resources: true
  html-math-method: mathml # See https://quarto.org/docs/reference/formats/html.html and https://pandoc.org/MANUAL.html#math-rendering-in-html
jupyter: python3
echo: false
---

<!--See https://quarto.org/docs/get-started/authoring/neovim.html for inline LaTeX information-->

The PDF version of this report is available for download [here](https://nevin-11.github.io/jsc370-project/project_pdf.pdf). Meanwhile, the project repository, including all static datasets and the README file, is located [here](https://github.com/nevin-11/nevin-11.github.io/tree/main/jsc370-project).

# Introduction

The Toronto Transit Commission (TTC) runs three heavy-rail subway lines: Line 1 Yonge-University, Line 2 Bloor-Danforth, and Line 4 Sheppard. Although the three lines are signficantly different in their locales and characteristics (for instance, Line 1 has many above-ground portions), they are all subject to delays of various lengths and causes, frustrating commuters.

The subway delays are captured on the Open Data portal of the City of Toronto, with the API documentation available [here](https://open.toronto.ca/dataset/ttc-subway-delay-data/). The data contains many variables, such as the time and location (i.e. which station) of the delays. We will focus on the 2025 subway delays, in particular their durations and causes.

Also, to allow us to explore a potential relationship between geography and delay lengths, we will use an unofficial dataset containing the co-ordinates of subway stations. This data can be found on the *We Saw a Chicken...* blog, with the datasets being introduced [here](https://scruss.com/blog/2005/12/14/toronto-subway-station-gps-locations); we will also incorporate station co-ordinates for the Line 1 Vaughan extensions that only opened in 2017.

Furthermore, the TTC has also published average weekday ridership data from September 2023 to August 2024 in PDF form [here](https://cdn.ttc.ca/-/media/Project/TTC/DevProto/Documents/Home/Transparency-and-accountability/Subway-Ridership-20232024.pdf?rev=4424b4bf53e443bd85031beab56649b7). We incorporate ridership into our analysis to give us a better idea of whether busier stations would have longer delays.

Finally, we will use the OpenMeteo dataset to capture the weather data at a given time; in particular, we will download and use a CSV file containing Toronto weather data for every hour of 2025 (please see [here](https://open-meteo.com/en/docs/historical-weather-api?timezone=America%2FNew_York&latitude=43.7064&longitude=-79.3986&start_date=2025-01-01&end_date=2025-12-31&hourly=temperature_2m,precipitation,rain,snowfall,relative_humidity_2m,wind_speed_10m) for specifics). This would help us identify whether weather-related factors, such as heavy snow, interact with subway delays.

In this analysis, we wish to discover the most important predictors of subway delay lengths. In addition, we wish to identify whether station ridership, the weekday-weekend difference, the weather (especially the presence or absence of snow), the line of the delay (1, 2, or 4), or the cause of the delay would influence delay length.

This analysis should help both commuters in helping them expect (and plan for) longer delays given background information such as the weather or time of the day, and potentially the TTC itself in helping them identify and address the causes of the longest delays.

# Methods
## Data Acquisition

```{python}
import requests
import pandas as pd
import time
import numpy as np
from datetime import datetime
import plotly.express as px
import seaborn as sns
import time
import re
import folium
from scipy import stats
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# See https://quarto.org/docs/authoring/tables.html
from IPython.display import Markdown
from tabulate import tabulate

# See https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html
from sklearn.metrics import mean_absolute_error, \
  root_mean_squared_error, r2_score

# See https://stackoverflow.com/questions/45761893/exporting-jupyter-notebook-to-pdf-with-offline-plotly-graph-missing-graphs
import plotly.io as pio
pio.renderers.default = 'notebook+pdf'

# See https://python-visualization.github.io/folium/latest/user_guide/plugins/marker_cluster.html
import folium.plugins
```

We will start by acquiring the 2025 subway delay data via the City of Toronto's Open Data API entry for "TTC Subway Delay Data" ([here](https://open.toronto.ca/dataset/ttc-subway-delay-data/)), specifically under the "TTC Subway Delay Data since 2025" subsection. No API keys are required. We then save the results of the API calls, convert the results into a Pandas dataframe, and remove results from 2026 (so that we work exclusively with 2025 data).

```{python}
# See https://open.toronto.ca/dataset/ttc-streetcar-delay-data/ (sic)
#  and https://open.toronto.ca/dataset/ttc-subway-delay-data/ for documentation
# Code below copied and/or adapted from https://open.toronto.ca/dataset/ttc-subway-delay-data/

BASE_URL = "https://ckan0.cf.opendata.inter.prod-toronto.ca"

url = f"{BASE_URL}/api/3/action/package_show"
params = {"id" : "ttc-subway-delay-data"}
package = requests.get(url, params=params, timeout=30).json()

for elem in package["result"]["resources"]:
  # Find the element named "TTC Subway Delay Data since 2025"
  if (elem.get("name") == "TTC Subway Delay Data since 2025"):
    break

url = f"{BASE_URL}/api/3/action/datastore_search"
all_results = []

# Get first batch of subway delay data manually
result = requests.get(
  url, 
  params={'id' : elem.get('id')}, 
  timeout=30
).json().get('result')

all_results.extend(result['records'])
next_str = result['_links']['next']

# Date of the last entry in <result>
# See https://www.codecademy.com/resources/docs/python/dates/strptime
last_date = datetime.strptime(result['records'][-1]['Date'], '%Y-%m-%d')

time.sleep(0.125)
    
while (last_date <= datetime(2025, 12, 31)): # Date
  # Keep fetching data via next_str
  result = requests.get(
    BASE_URL + next_str,  
    timeout=30
  ).json().get('result')

  if result['offset'] > result['total']:
    # We obtained all results, so break
    break

  all_results.extend(result['records'])
  next_str = result['_links']['next']

  # See https://www.codecademy.com/resources/docs/python/dates/strptime
  last_date = datetime.strptime(
    result['records'][-1]['Date'], 
    '%Y-%m-%d'
  )

  time.sleep(0.125)
```

```{python}
df = pd.DataFrame(all_results)

# Use Pandas's IDs instead of the API's
df.drop(['_id'], axis=1, inplace=True)

# Drop 2026 data (i.e. rows whose Date attribute contains '2026')
# See https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html
df.drop(
  df.loc[df.Date.str.contains('2026', regex=False)].index, 
  inplace=True
)
```

We then obtain the unofficial station co-ordinate (longtitude and latitude) datasets via the links embedded in [this post](https://scruss.com/blog/2005/12/14/toronto-subway-station-gps-locations/) on the *We Saw a Chicken...* blog. We then use Pandas' *read_csv* function to store the co-ordinates as Pandas dataframes, passing in one URL (i.e. one line) at a time.

We then use Google Maps to obtain the co-ordinates for the Line 1 Vaughan extension station. Finally, we concatenate the four sets of data (Line 1, Line 2, Line 4, and the Line 1 extension) into a single dataframe containing the co-ordinates of all heavy-rail TTC stations.

```{python}
# See https://scruss.com/blog/2005/12/14/toronto-subway-station-gps-locations/ for dataset information and links

# See http://scruss.com/wordpress/wp-content/yonge-university-spadina-NAD83.csv
line_1_coords = pd.read_csv('data/yonge-university-spadina-NAD83.csv', names = ['lat', 'long', 'station'])

# See http://scruss.com/wordpress/wp-content/bloor-danforth-NAD83.csv
line_2_coords = pd.read_csv('data/bloor-danforth-NAD83.csv', names = ['lat', 'long', 'station'])

# See http://scruss.com/wordpress/wp-content/sheppard-yonge-NAD83.csv
line_4_coords = pd.read_csv('data/sheppard-yonge-NAD83.csv', names = ['lat', 'long', 'station'])

# Use line 1 co-ordinates for interchanges
interchange_1_2 = line_2_coords.loc[line_2_coords.station.isin(['Spadina', 'St George', 'Yonge'])].index
line_2_coords.drop(interchange_1_2, axis=0, inplace = True)
line_4_coords.drop(
  line_4_coords.loc[line_4_coords.station == 'Sheppard-Yonge'].index,
  axis=0,
  inplace=True
)

# Station renamings
line_1_coords.loc[line_1_coords.station == 'Downsview', ['station']] = 'Sheppard West'
line_1_coords.loc[line_1_coords.station == 'Eglinton West', ['station']] = 'Cedarvale'
line_1_coords.loc[line_1_coords.station == 'Dundas', ['station']] = 'TMU'

# Match name formatting with <df>
line_1_coords.loc[line_1_coords.station == 'St Clair West', ['station']] = 'St. Clair West'
line_1_coords.loc[line_1_coords.station == 'St George', ['station']] = 'St. George'
line_1_coords.loc[line_1_coords.station == 'St Patrick', ['station']] = 'St. Patrick'
line_1_coords.loc[line_1_coords.station == 'St Andrew', ['station']] = 'St. Andrew'
line_1_coords.loc[line_1_coords.station == 'Bloor', ['station']] = 'Bloor-Yonge'
line_1_coords.loc[line_1_coords.station == 'St Clair', ['station']] = 'St. Clair'
line_1_coords.loc[line_1_coords.station == 'Sheppard', ['station']] = 'Sheppard-Yonge'
line_2_coords.loc[line_2_coords.station == 'Main Street', ['station']] = 'Main St.'
```

```{python}
# Create rows for the approximate coordinates of line 1 extension stations
# See Google Maps entry for each station (the "maps.app.goo.gl" link),
#  and look in the URL to extract the coordinates (look at the second set of coordinates for better results)
# Instruction for sharing Google Maps location can be found at https://support.google.com/maps/answer/7101463?hl=en&co=GENIE.Platform%3DDesktop

line_1_extension = [
  # https://maps.app.goo.gl/eimQcbR1vPmYWd7D9
  # https://www.google.ca/maps/place/43°45'12.6%22N+79°28'44.2%22W/@43.753499,-79.4798867
  [43.753499, -79.478955, 'Downsview Park'],

  # https://maps.app.goo.gl/3hbgck5vKAVSWBCU9
  # https://www.google.ca/maps/place/43°45'53.9%22N+79°29'29.0%22W/@43.764965,-79.4939609
  [43.764965, -79.491386, 'Finch West'],

  # https://maps.app.goo.gl/6hXmTYNAPmEyNn7W6
  # https://www.google.ca/maps/place/43°46'26.1%22N+79°29'59.4%22W/@43.773909,-79.5024019
  [43.773909, -79.499827, 'York University'],

  # https://maps.app.goo.gl/6fy3ZXuPhwSNhPVT6
  # https://www.google.ca/maps/place/43°46'37.5%22N+79°30'38.9%22W/@43.777085,-79.5133839
  [43.777085, -79.510809, 'Pioneer Village'],

  # https://maps.app.goo.gl/E5nm9N9ti4EDBtcz8
  # https://www.google.ca/maps/place/43°46'59.6%22N+79°31'25.5%22W/@43.783215,-79.5250354
  [43.783215, -79.523748, 'Highway 407'],

  # https://maps.app.goo.gl/7eDeqUSKsdymnNpo9
  # https://www.google.ca/maps/place/43°47'39.3%22N+79°31'39.0%22W/@43.794244,-79.5287745
  [43.794244, -79.527487, 'Vaughan Metropolitan Centre'],
]

line_1_extension_coords = pd.DataFrame(
  line_1_extension, 
  columns = ['lat', 'long', 'station']
)
```

```{python}
# See https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat
station_coords = pd.concat([
  line_1_coords,
  line_1_extension_coords,
  line_2_coords,
  line_4_coords
])

station_coords.reset_index(inplace=True)
station_coords.drop(['index'], axis=1, inplace=True)

station_coords = station_coords.iloc[:, [2, 1, 0]]
```

Next, we incorporate the official September 2023 to August 2024 weekday ridership data, sourced from [here](https://cdn.ttc.ca/-/media/Project/TTC/DevProto/Documents/Home/Transparency-and-accountability/Subway-Ridership-20232024.pdf?rev=4424b4bf53e443bd85031beab56649b7). The PDF has already been manually converted to a CSV file, so we can simply use *read_csv* to convert that file to a dataframe.

```{python}
station_ridership_df = pd.read_csv(
  'data/ttc_ridership.csv', 
  encoding='ISO-8859-1'
)
```

We then obtain the meaning of the delay codes from the "Code Descriptions" section of the official subway delay API documentation (available [here](https://open.toronto.ca/dataset/ttc-subway-delay-data/)). Specifically, we download the CSV file from that section of the documentation, read it into Pandas via *read_csv*, and perform basic formatting on the code meanings.

```{python}
delay_meaning = pd.read_csv(
  'data/Code Descriptions.csv', encoding='ISO-8859-1'
)
delay_meaning.drop(['_id'], axis=1, inplace=True)
delay_meaning.rename(
  {'CODE' : 'Code', 'DESCRIPTION' : 'Meaning'}, axis=1, inplace=True
)

# Delete all characters that are not alphabetical, parantheses, slashes, or spaces
# See https://www.w3schools.com/python/python_regex.asp
delay_meaning.Meaning = delay_meaning.Meaning.apply(
  lambda x : re.sub("[^a-zA-Z()/ ]", "", x)
)
```

Finally, we read in Toronto weather data for every hour of 2025, sourced from OpenMeteo and containing the following metrics: temperature, precipitation, rain, snowfall, relative humidity, and wind speed (10m). Although the file has already been saved to the project repository, it is also downloadable via the "Download CSV" button of [this OpenMeteo page](https://open-meteo.com/en/docs/historical-weather-api?timezone=America%2FNew_York&latitude=43.7064&longitude=-79.3986&start_date=2025-01-01&end_date=2025-12-31&hourly=temperature_2m,precipitation,rain,snowfall,relative_humidity_2m,wind_speed_10m).

```{python}
# See https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
weather_df = pd.read_csv(
  'data/open-meteo-43.69N79.41W165m.csv', 
  skiprows=4, # Skip first 4 rows (row 4: "time,temperature_2m (°C)...")
  names=[
    'Time', 'Temperature', 'Precipitation', 'Rain', 
    'Snowfall', 'Humidity', 'Wind Speed'
  ],
  encoding='ISO-8859-1'
)

# Timestamp format: 2025-01-01T00:00
weather_df['Date'] = weather_df.Time.apply(
  lambda x: x.split('T')[0]
)

# See https://docs.python.org/3/library/datetime.html
weather_df['Hour'] = weather_df.Time.apply(
  lambda x: datetime.strptime(x.split('T')[1], '%H:%M').hour
)

# Delete "Time" column
weather_df.drop(['Time'], axis=1, inplace=True)
```

## Data Cleaning

We focus our data-cleaning efforts on the delay dataframe. All other dataframes (i.e. station co-ordiates, ridership, delay meaning, and weather data) already contain our desired information and no malformed data, so they could be considered to be *already clean*.

We start by cleaning up the station names; among other changes, we now use normal capitalization, so "KENNEDY BD STATION" became "Kennedy". We also remove the few rows with a misspelt or malformed station name.

```{python}
regular_station_names = [
  # Exclude names covered in special_station_names below

  # Multi-word names
  # Line 1
  "Vaughan Metropolitan Centre", "Highway 407", "Pioneer Village", 
  "York University", "Finch West", "Downsview Park", "Sheppard West",
  "Lawrence West", "Queen's Park", "York Mills", "North York Centre",
  # Other lines
  'Royal York', 'Old Mill', 'High Park', 'Dundas West', 'Castle Frank', 
  'Victoria Park', 'Don Mills',

  # Single-word names
  # Line 1
  'Wilson', 'Yorkdale', 'Glencairn', 'Dupont', 'Museum', 'Osgoode', 'Union', 
  'King', 'Queen', 'College', 'Wellesley', 'Rosedale', 'Summerhill', 'Davisville', 'Eglinton', 'Lawrence', 'Finch',
  # Line 2
  'Kipling', 'Islington', 'Jane', 'Runnymede', 'Keele', 'Lansdowne', 'Dufferin',
  'Ossington', 'Christie', 'Bathurst', 'Bay', 'Sherbourne', 'Broadview', 'Chester', 'Pape', 'Donlands', 'Greenwood', 'Coxwell', 'Woodbine', 'Warden', 'Kennedy',
  # Line 4
  'Bayview', 'Bessarion', 'Leslie',

  # Interchange stations
  'St. George', 'Spadina', 'Sheppard-Yonge'
  ]

# See the body of the extract_station_name function below
special_station_names = [
  'Vaughan Metropolitan Centre', 'Main St.', 
  'Cedarvale', 'TMU', 'Bloor-Yonge',
  'St. Clair West', 'St. Patrick', 'St. Andrew', 'St. Clair'
  ] 

all_station_names = regular_station_names + special_station_names
```

```{python}
def extract_station_name(station):
  # Special cases
  if station in ['VMC STATION', 'VMC']:
    return 'Vaughan Metropolitan Centre'
  elif station in ['MAIN STATION', 'MAIN',
                   'MAIN STREET STATION', 'MAIN STREET']:
    return 'Main St.'

  # 'St' vs 'St.' 
  if station in ['ST CLAIR WEST STATION', 'ST CLAIR WEST',
                   'ST. CLAIR WEST STATION', 'ST. CLAIR WEST']:
    return 'St. Clair West' 
  elif station in ['ST PATRICK STATION', 'ST PATRICK',
                   'ST. PATRICK STATION', 'ST. PATRICK']:
    return 'St. Patrick'
  elif station in ['ST ANDREW STATION', 'ST ANDREW',
                   'ST. ANDREW STATION', 'ST. ANDREW']:
    return 'St. Andrew'
  elif station in ['ST CLAIR STATION', 'ST CLAIR',
                   'ST. CLAIR STATION', 'ST. CLAIR']:
    return 'St. Clair'
  elif 'ST GEORGE' in station:
    return 'St. George'

  # Renamed and interchange stations 
  if station in ['EGLINTON WEST STATION', 'EGLINTON WEST',
                 'CEDARVALE STATION', 'CEDARVALE']:
    return 'Cedarvale'
  elif station in ['DUNDAS STATION', 'DUNDAS', 
                   'TMU STATION', 'TMU']:
    return 'TMU' # Also accounts for the fact that it is "TMU" not "Tmu"
  elif station in ['BLOOR STATION', 'BLOOR', 'YONGE STATION', 'YONGE']:
    return 'Bloor-Yonge'
  
  for s in regular_station_names:
    # Return first station name found 
    #  even if <station> has multiple station names by mistake
    if s.lower() in station.lower():
      return s
  
  # No station names found, return None
  return None
```

```{python}
df.Station = df.Station.apply(extract_station_name)
malformed_stations_idx = df[~df.Station.isin(all_station_names)].index
df.drop(index=malformed_stations_idx, axis=0, inplace=True)
```

### Data Types

We then clean up the data types of the variables (features). For instance, we convert the "Line" feature to instead store the line number (i.e. 1, 2, or 4) as a categorical variable.

```{python}
# See https://pandas.pydata.org/docs/user_guide/categorical.html

df['Min Delay'] = df['Min Delay'].astype(float)
df['Min Gap'] = df['Min Gap'].astype(float)

# For the Vehicle column, replace 0 with NaN, then convert as categorical
df.loc[df['Vehicle'] == '0', ['Vehicle']] = np.nan 
df['Vehicle'] = df['Vehicle'].astype("category") 

# Line is categorical in YU (1), BD (2), and SHP (4)
# Other values in the line feature are invalid and should be removed
malformed_lines_idx = df[~(df['Line'].isin(['YU', 'BD', 'SHP']))].index
df.drop(index=malformed_lines_idx, axis=0, inplace=True)

# Then convert the line feature to store the number 1, 2, or 4 as a categorical feature
line_dict = {'YU' : 1, 'BD' : 2, 'SHP' : 4, np.nan : np.nan}
df['Line'] = df['Line'].apply(lambda x: line_dict[x]).astype("category")

# Replace 'None' directions with np.nan for easier processing
df.loc[df['Bound'] == 'None', ['Bound']] = np.nan
df['Bound'] = df['Bound'].astype("category") 

# Make delay type (code) and station categorical
df['Code'] = df['Code'].astype("category") 
df['Station'] = df['Station'].astype("category") 
```

We then convert the temporal variables (i.e. month, day, hour, and minute of delay) to float variables; since we exclusively analyze 2025 delays, it is not necessary to store the year separately. We also encode the days of the week as numerical variables; we will eventually make this feature categorical *after* feature engineering (to avoid the new features inadvertently having a categorical datatype).

```{python}
# See https://www.w3schools.com/python/python_regex.asp

# Allows string-based operations, such as split, on <date>
df['Date'] = df['Date'].astype(str) 

# Rename day-of-week column for clarity and to avoid name collision
df.rename({'Day' : 'Day of Week'}, axis=1, inplace=True)

# Year, month, and day come from df.Date
df['Month'] = df['Date'].apply(lambda date : int(date.split('-', 2)[1]))
df['Day'] = df['Date'].apply(lambda date : int(date.split('-', 2)[2]))

# Hour and minute come from df.Time
df['Hour'] = df['Time'].apply(lambda x : float(x.split(':', 1)[0]))
df['Minute'] = df['Time'].apply(lambda x : float(x.split(':', 1)[1]))
```

```{python}
def day_of_the_week(day):
  days = {
    'Monday' : 0,
    'Tuesday' : 1,
    'Wednesday' : 2,
    'Thursday' : 3,
    'Friday' : 4,
    'Saturday' : 5,
    'Sunday' : 6
  }

  if day in days.keys():
    return days[day]
  else:
    # Invalid day
    return np.nan

df['Day of Week'] = df['Day of Week'].apply(day_of_the_week)
```

### Handling Null Values

We now turn our attention to null values. The only columns with null values remaining are the direction and vehicle (i.e. car number) columns. Other columns with problematic values were already handled above; for example, rows with misspelt station names have already been dropped.

We note that neither the direction nor the vehicle column is important. Specifically, in the case of Line 2, both westbound and eastbound trains would lead to more suburban parts of Toronto (Etobicoke and Scarborough respectively). Also, since it would not be enlightening to find a relationship (if any) between a specific subway car and the delay length associated with it, we can also safely drop the vehicle number column.

We also drop the "Min Gap" column. Although the Open Data portal did not give an official explanation for that column's meaning, the Min Gap column seems to simply represent the gap between the delayed train and the next train, or 0 in case of a zero-minute delay (more details on such delays below). Therefore, the continued inclusion of the column would constitute data leakage, and we should remove that column.

```{python}
df.drop(['Min Gap', 'Bound', 'Vehicle'], axis=1, inplace=True)
```

### Removing Outliers and Zeroes from Delay Lengths

We note that as of now, the distribution of delay times is strongly right-skewed. Although the kernel density plot (KDE) below is presented with a log transformation, the delay times remain very right-skewed.

```{python}
#| label: fig-kde
#| fig-cap: The kernel density plot (KDE) for the uncleaned delay times

log1p_delay = np.log1p(df['Min Delay'])

# See https://seaborn.pydata.org/generated/seaborn.kdeplot.html
sns.kdeplot(
  data=log1p_delay
).set(
  title='Distribution of Delay Durations (in Minutes)',
  xlabel='Natural Log of (Delay Time + 1)'
);
```

We note not only the presence of zero-minute delays, but also of delays with extreme lengths, the longest delay being 900 minutes (or 15 hours).

```{python}
#| label: tbl-min-delay
#| tbl-cap: Summary statistics for the length of delays

# See https://quarto.org/docs/authoring/tables.html

def summary_statistics(df, ftrs, names):
  info = [
    [col, # Name of feature
    np.round(df[col].mean(), 4),
    np.round(df[col].std(), 4),
    np.round(np.min(df[col]), 4),
    np.round(np.median(df[col]), 4),
    np.round(np.max(df[col]), 4)]
    for col in ftrs
  ]

  for i in range(len(info)):
    info[i][0] = names[i]

  return Markdown(tabulate(
    info,
    headers=[
      'Feature', 'Mean', 'Standard Deviation', 
      'Minimum', 'Median', 'Maximum'
    ]
  ))

summary_statistics(df, ['Min Delay'], ['Delay Length'])
```

The impact of zero-minute delays to commuters, if they could be considered genuine delays at all, is negligle. Removing them from our analysis would not affect its utilty to stakeholders; on the other hand, removing such delays help focus our analysis on actual delays (with a non-zero duration).

Meanwhile, we consider two hours to be an adequate upper bound as to the delay lengths that we would analyze here. This allows us to continue to analyze long delays that commuters could plan for in advance, while preventing excessively-long delays (such as the fifteen-hour delay seen above) from distorting our analysis.

We therefore remove delays whose length is either zero or (strictly) above two hours. Approximately 8600 delays remain after this point, which is still adequate for our analysis.

```{python}
df.drop(
  df[(df['Min Delay'] == 0) | (df['Min Delay'] >= 120)].index,
  axis=0,
  inplace=True
)
```

## Feature Engineering

We sine-encode the temporal attributes (i.e. month, day, hour, minute, and day of the week), and add a column indicating whether the delay occurred on a weekend. We are also now able to make the day of the week a categorical variable.

We also add a column representing the crow-flies distance of each subway station from Union Station as an approximate measure of that station's distance from the Financial District (which is a destination for many commuters).

```{python}
# Days of the month 
def day_encoder(month, day):
  if month == 2:
    # February so 28 days
    return np.sin(2 * np.pi * day / 28), np.cos(2 * np.pi * day / 28)
  elif month in [1, 3, 5, 7, 8, 10, 12]:
    # Months with 31 days
    return np.sin(2 * np.pi * day / 31), np.cos(2 * np.pi * day / 31)
  else:
    # Months with 30 days
    return np.sin(2 * np.pi * day / 30), np.cos(2 * np.pi * day / 30)

# See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html
df['Sine Day'] = df.apply(
  lambda x : day_encoder(x.Month, x.Day)[0], 
  axis=1
)
df['Cosine Day'] = df.apply(
  lambda x : day_encoder(x.Month, x.Day)[1], 
  axis=1
)
```

```{python}
# All other features
df['Sine Minute'] = df.Minute.apply(
  lambda x : np.sin(2 * np.pi * x / 60)
)
df['Cosine Minute'] = df.Minute.apply(
  lambda x : np.cos(2 * np.pi * x / 60)
)

df['Sine Hour'] = df.Hour.apply(lambda x : np.sin(2 * np.pi * x / 24))
df['Cosine Hour'] = df.Hour.apply(lambda x : np.cos(2 * np.pi * x / 24))

df['Sine Month'] = df.Month.apply(
  lambda x : np.sin(2 * np.pi * x / 12)
)
df['Cosine Month'] = df.Month.apply(
  lambda x : np.cos(2 * np.pi * x / 12)
)

df['Sine Day of Week'] = df['Day of Week'].apply(
  lambda x : np.sin(2 * np.pi * x / 7)
)
df['Cosine Day of Week'] = df['Day of Week'].apply(
  lambda x : np.cos(2 * np.pi * x / 7)
)

# It is now safe to make Day of Week categorical 
df['Day of Week'] = df['Day of Week'].astype("category") 

df['Weekend'] = df['Day of Week'].isin([5, 6])
```

```{python}
# See https://scruss.com/wordpress/wp-content/yonge-university-spadina-NAD83.csv
union_lat, union_long = 43.645722666, -79.380462258

# From Week 9 lab starter code (https://github.com/JSC370/JSC370-2026/blob/main/labs/lab9/lab09-xgboost.ipynb)
def haversine_km(lat1, lon1, lat2, lon2):
  R = 6371
  dlat = np.radians(lat2 - lat1)
  dlon = np.radians(lon2 - lon1)

  a = (
    np.sin(dlat/2)**2 + 
    np.cos(np.radians(lat1))*np.cos(np.radians(lat2))*np.sin(dlon/2)**2
  )

  return R * 2 * np.arcsin(np.sqrt(a))

station_coords['Distance from Union'] = haversine_km(
  station_coords.lat,
  station_coords.long,
  union_lat,
  union_long
)
```

We have performed the feature engineering on the split dataframes (i.e. before we merge them) for computational efficiency. For instance, instead of calculating the crow-flies distance once *per delay* on the merged dataframe (for a total of around 8600 times), we calculate it once *per station* on the stations co-ordinates dataframe (for a total of around 70 times).

## Data Exploration

We merge the (cleaned) datasets before performing data analysis on the merged dataset.

```{python}
# See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

df = df.merge(
  station_coords, left_on='Station', 
  right_on='station', suffixes=[None, '_right']
)
df = df.merge(
  station_ridership_df, left_on='Station', 
  right_on='station', suffixes=[None, '_right']
)
df = df.merge(
  weather_df, left_on=['Date', 'Hour'],
  right_on=['Date', 'Hour'], suffixes=[None, '_right']
)
```

```{python}
# Rename to match name formats
new_col_names = {
  'lat' : 'Latitude',
  'long' : 'Longtitude',
  'ridership' : 'Ridership'
}
df.rename(new_col_names, axis=1, inplace=True)

cols_right = [
  col for col in df.columns if '_right' in col
]
df.drop(cols_right, axis=1, inplace=True)

# Drop redundant or unnecessary columns
df.drop(['station', 'Date', 'Time'], axis=1, inplace=True)
```

### Distribution of Delay Causes

The distribution of delay types are very uneven. Specifically, a few causes of delays are very frequent, whereas many causes of delays are rare. We also note that some of the most frequent causes of delays pertain to the state of the passengers themselves (e.g. disorderly patrons or security risks), with PUOPO (door-related issues) being an exception.

```{python}
delay_types = df.Code.value_counts().reset_index()
delay_types = delay_types.loc[delay_types['count'] > 0]
delay_types.rename({'count' : 'Count'}, axis=1, inplace=True)
delay_types = delay_types.merge(delay_meaning, on='Code')
```

```{python}
#| label: fig-delay-counts
#| fig-cap: Distribution of Causes of TTC Delays

# See https://quarto.org/docs/authoring/figures.html for "fig-" above

fig = px.bar(
  delay_types, x='Code', y='Count', custom_data=['Meaning'],
  labels={'Count' : 'Frequency'},
  title='Distribution of Delay Causes'
)

fig.update_traces(
  hovertemplate=(
    'Code: %{x} <br>' + 
    'Meaning: %{customdata[0]} <br>' + 
    'Count: %{y} <extra></extra>'
  )
)

fig.show()
```

### Distribution of Delays for Weekdays versus Weekends

We observe that 78% of the 2025 delays occurred during a weekday, more than the 71% (5/7) that we would expect if the number of delays are equally distributed across the days of the week. We also note that the mean weekday delay duration is lower; we will further explore this observation in the next section.

```{python}
#| label: tbl-weekday-weekend
#| tbl-cap: Distribution of delays with respect to the weekday-weekend difference

# See https://quarto.org/docs/authoring/tables.html

weekday_count = df.loc[~df.Weekend].shape[0]
weekend_count = df.loc[df.Weekend].shape[0]

total_count = df.shape[0]
weekday_prop = weekday_count / total_count
weekend_prop = weekend_count / total_count

weekday_mean_delay = np.mean(df.loc[~df.Weekend, ['Min Delay']])
weekend_mean_delay = np.mean(df.loc[df.Weekend, ['Min Delay']])

weekday_weekend = [
  ['Weekday', weekday_count, 
  np.round(weekday_prop, 4), np.round(weekday_mean_delay, 4)],
  ['Weekend', weekend_count, 
  np.round(weekend_prop, 4), np.round(weekend_mean_delay, 4)]
]

Markdown(tabulate(
  weekday_weekend, headers=[
    'Type of Day', 'Number of Delays', 
    'Proportion of Delays', 'Mean Delay Duration (in Minutes)'
  ])
)
```

### Distribution of Delays on Different Lines

We note that over the course of 2025, Line 4 Sheppard has far fewer delays than the two other subway lines. However, this is plausible given its lower ridership and the fact that Line 4 is the newest line of the heavy-rail subway system. Although Line 4 delays tend to be the longest on average, we will defer the analysis thereof to the next section.

```{python}
#| label: tbl-lines
#| tbl-cap: Distribution of delays with respect to the subway lines

# See https://quarto.org/docs/authoring/tables.html

line_one_delays = df.loc[df.Line == 1, ['Min Delay']]
line_two_delays = df.loc[df.Line == 2, ['Min Delay']]
line_four_delays = df.loc[df.Line == 4, ['Min Delay']]

line_one_count = line_one_delays.shape[0]
line_two_count = line_two_delays.shape[0]
line_four_count = line_four_delays.shape[0]

total_count = df.shape[0]
line_one_prop = line_one_count / total_count
line_two_prop = line_two_count / total_count
line_four_prop = line_four_count / total_count

line_one_mean_delay = np.mean(line_one_delays)
line_two_mean_delay = np.mean(line_two_delays)
line_four_mean_delay = np.mean(line_four_delays)

line_delays = [
  ['1 (Yonge-University)', line_one_count, 
  np.round(line_one_prop, 4), np.round(line_one_mean_delay, 4)],
  ['2 (Bloor-Danforth)', line_two_count, 
  np.round(line_two_prop, 4), np.round(line_two_mean_delay, 4)],
  ['4 (Sheppard)', line_four_count, 
  np.round(line_four_prop, 4), np.round(line_four_mean_delay, 4)]
]

Markdown(tabulate(
  line_delays, headers=[
    'Line', 'Number of Delays', 'Proportion of Delays', 
    'Mean Delay Duration (in Minutes)'
  ])
)
```

### Distribution of Delays Counts and Durations Across Stations

```{python}
station_df = station_coords.reset_index()

station_df['Mean'] = station_df['station'].apply(
  lambda x: np.round(np.mean(df.loc[df.Station == x, ['Min Delay']]), 4)
)

station_df['Count'] = station_df.station.apply(
  lambda x: df.loc[df.Station == x].shape[0]
)

station_df['Distance from Union'] = \
  station_df['Distance from Union'].apply(lambda x: np.round(x, 2))

# Impute stations without delays (i.e. Bayview)
station_df.fillna(0, inplace=True)

# Most delay-prone stations first
station_df.sort_values(['Count'], ascending=False, inplace=True)
```

Now that problematic delay lengths have been removed, we re-plot the KDE for the remaining delay lengths, again applying a logarithmic transformation on the KDE. We note that the data is now less right-skewed that before, but still significantly right-skewed. This suggest that the transformation itself may not have been helpful.

```{python}
#| label: fig-kde-clean
#| fig-cap: The kernel density plot (KDE) for the cleaned delay times

log1p_delay_clean = np.log1p(df['Min Delay'])

# See https://seaborn.pydata.org/generated/seaborn.kdeplot.html
sns.kdeplot(
  data=log1p_delay_clean
).set(
  title='Distribution of Cleaned Delay Durations (in Minutes)',
  xlabel='Natural Log of (Delay Time + 1)'
);
```

The following table presents summary statistics for the delay lengths, both at a per-delay and a per-station level; the latter means that we only consider the mean delay duration at each subway station. Since Bayview staion has in fact had no delays within the dataset, we will *not* factor that station into consideration when calculating summary statistics at a per-station level; this is to avoid distorting the statistics.

We note that per-station average delay times has become much less dispersed once we remove North York Centre station from consideration. Given that there is only one delay in the dataset which is associated with that station, we can safely consider that station to be an outlier.

```{python}
#| label: tbl-min-delay-clean
#| tbl-cap: Summary statistics for the cleaned delay lengths

# See https://quarto.org/docs/authoring/tables.html

station_df_bis = station_df.loc[
  station_df.station != 'Bayview'
]

station_df_no_nyc = station_df.loc[
  ~station_df.station.isin(['Bayview', 'North York Centre'])
]

lst = [
  [
    'Individual Delays',
    np.round(df['Min Delay'].mean(), 4),
    np.round(df['Min Delay'].std(), 4),
    np.round(np.min(df['Min Delay']), 4),
    np.round(np.median(df['Min Delay']), 4),
    np.round(np.max(df['Min Delay']), 4)
  ],
  [
    'Per-Station Average',
    np.round(np.mean(station_df_bis.Mean), 4),
    np.round(station_df_bis.Mean.std(), 4),
    np.round(np.min(station_df_bis.Mean), 4),
    np.round(np.median(station_df_bis.Mean), 4),
    np.round(np.max(station_df_bis.Mean), 4)
  ],
  [
    'Per-Station Average (Excluding North York Centre)',
    np.round(np.mean(station_df_no_nyc.Mean), 4),
    np.round(station_df_no_nyc.Mean.std(), 4),
    np.round(np.min(station_df_no_nyc.Mean), 4),
    np.round(np.median(station_df_no_nyc.Mean), 4),
    np.round(np.max(station_df_no_nyc.Mean), 4)
  ]
]


Markdown(tabulate(
  lst,
  headers=[
    'Delay Duration Type', 'Mean', 'Standard Deviation', 
    'Minimum', 'Median', 'Maximum'
  ]
))
```

Finally, the following maps shows the number of delays, as well as the mean delay length, for every station. We could observe that several terminus stations (i.e. Kipling, Kennedy, and Finch) have many associated delays, alongside transfer stations between Lines 1 and 2 (except Spadina) and other stations (e.g. Wilson and Eglinton).

This propensity for delays at those stations may be attributed to their high ridership and importance within the TTC ecosystem. For instance, Kennedy station is a hub to many Scarborough bus routes, and Eglinton station had already been busy before Line 5 opened.

Moreover, since Bayview station is associated with no delays, it is shown below as having a average delay duration of zero minutes.

```{python}
#| label: fig-delay-count-map
#| fig-cap: Map of delay counts and mean delay durations per subway station

# See https://python-visualization.github.io/folium/latest/user_guide/plugins/featuregroup_subgroup.html 

pts = station_df[
  ["station", "lat", "long", "Count", "Mean"]
].dropna().drop_duplicates()

m = folium.Map(
    location=[pts["lat"].mean(), pts["long"].mean()],
    zoom_start=11,
    tiles="CartoDB positron"
)

fg = folium.FeatureGroup(control=False)
m.add_child(fg)

g1 = folium.plugins.FeatureGroupSubGroup(fg, "Delay Counts")
m.add_child(g1)

# Hide this layer by default  
# See https://python-visualization.github.io/folium/latest/reference.html (FeatureGroupSubGroup section)
g2 = folium.plugins.FeatureGroupSubGroup(
  fg, "Mean Delay Durations", show=False
)
m.add_child(g2)

# Copied and adapted from Week 3 Slide 46 (https://jsc370.github.io/JSC370-2026/slides/03-eda-viz/JSC370-slides-03.html#/interactive-map-2)
for _, r in pts.iterrows():
  folium.CircleMarker(
    location=[r["lat"], r["long"]],
    radius=(r['Count'] / 50) + 0.1,
    popup=(
      f'Station: {r["station"]}\n' +
      f'Number of Delays in 2025: {r['Count']}\n' +
      f'Station Mean Delay Length: {r['Mean']:.2f} minutes'
    ),
    fill=True,
    fill_opacity=0.8,
    opacity=0.8,
  ).add_to(g1)

  folium.CircleMarker(
    location=[r["lat"], r["long"]],
    radius=(r['Mean'] / 3) + 0.1,
    popup=(
      f'Station: {r["station"]}\n' +
      f'Number of Delays in 2025: {r['Count']}\n' +
      f'Station Mean Delay Length: {r['Mean']:.2f} minutes'
    ),
    fill=True,
    color='gold',
    fill_opacity=0.8,
    opacity=0.8,
  ).add_to(g2)

folium.LayerControl(collapsed=False).add_to(m)

m
```

### Other Numerical Features

We observe that all values of the following features are plausible, and there are no unreasonable data (e.g. negative ridership or stations outside of Toronto or Vaughan). Despite there being a 35.8-degree day in the dataset, that day actually corresponds to 24 June (i.e. the summer), so it is plausible.

```{python}
#| label: tbl-summary-statistics
#| tbl-cap: Summary statistics for other important numerical columns

numeric_ftrs = [
  'Longtitude', 'Latitude', 'Distance from Union', 'Ridership',
  'Temperature', 'Precipitation', 'Rain', 'Snowfall', 
  'Humidity', 'Wind Speed'
]

summary_statistics(df, numeric_ftrs, numeric_ftrs)
```

### Longest Delays

Since many delays are short, we focus on examining the (five) longest delays to uncover any potential patterns among such delays. This will guide our preliminary questions and results, and will help us put our models into context.

The longest delays genearlly occurred during the weekday at lower-ridership stations further away from the downtown core. With regard to the weather, all of the below delays occurred on cold, precipitation-free, fairly humid days with strong winds. This hints at a possible correlation between ridership and/or weather on one hand, and delay lengths on the other hand.

```{python}
#| label: tbl-longest
#| tbl-cap: The five longest delays

# See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html

Markdown(
  df.sort_values(['Min Delay'], ascending=False).head().to_markdown(index=False)
)
```

### Models

We will build and compare two tree-based models.

Random forest is a bagging-based model involving the production of many trees, each trained on a random subset of features. When we wish to make a prediction (in this case, of delay length), we would predict the mean value among all of the trees' predictions.

On the other hand, XGBoost is a boosting-based model where each tree is sequentially improved based on the residuals of its predecessor. The trees are then summed up to produce a final tree.

We will use the same set of metrics to compare the two delay-prediction models: $R^2$ (proportion of variance explained) relates to the ability of our model to capture variations in delay durations, RMSE (root mean squared error) helps us perceive the average error (distance) between the model's predicted delay times and the actual delay times, and MAE (mean absolute error) serves as another metric of error but is robust to outliers, of which our dataset has a few in the form of long delay times.

To ensure fairness in model-tuning, we will train the models on the same train-validation-test split (60% training, 20% each validation and testing); both models would receive the same training, validation, and test sets.

We will then perform a grid search for the best hyperparameter combination: for each model, we will test four hyperparameters, trying out three values for each for a total of 81 combinations. Finally, the usage of the same metrics to compare the two models further guarantees the fairness of the comparison.

```{python}
# Drop numerical versions of temporal attributes
model_df = df.drop(
  ['Day', 'Minute', 'Hour', 'Month', 'Day of Week'], axis=1
)

# See https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html
model_df = pd.get_dummies(
  model_df, columns=['Station', 'Code', 'Line'], drop_first=False
)

train_val, test_df = train_test_split(
  model_df, train_size=0.8, random_state=11
)
train_df, val_df = train_test_split(
  train_val, train_size=0.75, random_state=11
) # Train size = 0.8 * 0.75 = 0.6 of the original dataset

# Export to tuning directory for hyperparameter tuning
train_df.to_csv('tuning/train.csv')
val_df.to_csv('tuning/val.csv')
test_df.to_csv('tuning/test.csv')
```

```{python}
X_train = train_df.drop(['Min Delay'], axis=1)
y_train = train_df['Min Delay']

X_val = val_df.drop(['Min Delay'], axis=1)
y_val = val_df['Min Delay']

X_test = test_df.drop(['Min Delay'], axis=1)
y_test = test_df['Min Delay']
```

# Results
## Statistical Testing

We use statistical tests to explore the relationship between delay times and the following features: line (1 vs. 2 vs. 4), precipitation, station ridership, and the weekday-weekend difference. We test one such feature at a time, holding all other features constant.

We will use SciPy's implementations of the following hypothesis tests: the Kruskal-Wallis H-test, the Mann-Whitney U-test, and the t-test. Our null hypotheses are as follows:

- Kruskal-Wallis H-test: The median delay length is the same across lines 1, 2, and 4 (see SciPy documentation [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kruskal.html)).
- t-test: There is no linear correlation between precipitation (or ridership) and delay length. In other words, if we were to fit a simple linear regression model only on that specific feature, its slope would be zero.
- Mann-Whitney U-test: The distribution of weekday and weekend delay times are the same.

```{python}
#| label: tbl-tests
#| tbl-cap: Hypothesis testing for the four aforementioned features.

# See https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.linregress.html, https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html, and https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kruskal.html

line_p_value = stats.kruskal(
  line_one_delays, line_two_delays, line_four_delays
).pvalue[0]

precipitation_reg = stats.linregress(
  df.Precipitation, df['Min Delay']
)

ridership_reg = stats.linregress(
  df.Ridership, df['Min Delay']
)

weekend_p_value = stats.mannwhitneyu(
  df.loc[df.Weekend, ['Min Delay']],
  df.loc[~df.Weekend, ['Min Delay']]
).pvalue[0]

tests = [
  [
    'Line (1, 2, or 4)', 'Kruskal-Wallis H-test', '', '', 
    line_p_value
  ],
  [
    'Precipitation', 't-test', np.round(precipitation_reg.rvalue, 4),
    precipitation_reg.slope, np.round(precipitation_reg.pvalue, 4)
  ],
  [
    'Ridership', 't-test', np.round(ridership_reg.rvalue, 4),
    ridership_reg.slope, np.round(ridership_reg.pvalue, 4)
  ], 
  ['Weekday vs Weekend', 'Mann-Whitney U-test', '', '', weekend_p_value]
]

# See https://quarto.org/docs/authoring/tables.html
Markdown(tabulate(
  tests, headers=['Feature', 'Test', 'Pearson R', 'Slope', 'p-value']
))
```

Due to the high p-value of 0.733, we fail to reject the null hypothesis with respect to precipitation and therefore conclude that precipitation, in isolation, is not a meaningful predictor of delay length.

In addition, although we reject the null hypothesis for the ridership t-test due to the p-value of 0.017, thus concluding that there is a linear relationship between station ridership and delay length, we note that the slope of $-3.48*10^{-6}$ is so small to the extent that ridership has a negligible impact on delay lengths. The Pearson r-value of -0.026 also corroborates the notion that ridership and delay length are *de facto* unrelated.

On the other hand, the Mann-Whitney U-test for the weekday-weekend difference has a convincingly low p-value of $4.98*10^{-11}$. We therefore reject the null hypothesis that the distribution of weekday and weekend delay times are the same. In other words, the difference between the weekday and weekend delay times is statistically significant, and recall that weekend delays tend to be longer per the previous section.

In addition, the Kruskal-Wallis H-test for subway lines also has a extremely low p-value ($8.05*10^{-8}$). Therefore, we also reject the null with regard to the subway lines, and conclude that the median delay length is *not* uniform across lines 1, 2, and 4.

## Boxplots

We now use boxplots to visualize the two features (line and weekday-weekend difference) for which we have rejected the null hypotheses.

We note that although the median delay length is five minutes within each subway line, their distributions significantly differ. Specifically, Line 4 Sheppard delays tend to be more concentrated about the five-minute median (hence its box on the boxplot being more narrow). On the other hand, Line 1 Yonge-University seems to have many outlier delay times, since the boxplot shows many close-together dots (outliers) for that subway line.

```{python}
#| label: fig-delay-lines
#| fig-cap: Impact of the subway line on delay times

# Impart an order (1, 2, then 4) to the lines
# See https://pandas.pydata.org/docs/user_guide/categorical.html#sorting-and-order and https://pandas.pydata.org/docs/reference/api/pandas.Categorical.reorder_categories.html#pandas.Categorical.reorder_categories
df.Line = df.Line.cat.reorder_categories([1, 2, 4], ordered=True)

# category_orders means the graph would respect category order (1, 2, 4)
# See https://stackoverflow.com/questions/68348141/wrong-order-of-values-on-x-axes-when-build-charts-with-groups-using-plotly-py
fig = px.box(
  df, x='Min Delay', y='Line', log_x=True,
  labels={'Min Delay' : 'Delay Length (in Minutes)'}, 
  category_orders={'Line': df.Line},
  title='Distribution of Delay Durations per Subway Line'
)

fig.update_traces(
  hovertemplate=(
    'Delay Length: %{x} minutes <br>' +
    'Line: %{y} <extra></extra>'
  )
)

# Force y-axis to categorical order (lest Line 3 shows up)
# See https://plotly.com/python/categorical-axes/
fig.update_yaxes(type='category')

fig.show()
```

Also, we consider the following boxplot, which shows the difference in delay duration distributions with respect to weekdays and weekends. Although the median delay length is five minutes for both weekdays and weekends, weekend delays indeed tend to be longer, as seen with the weekend box being further to the right than the weekday box in the boxplot below.

```{python}
#| label: fig-delay-weekday-weekend
#| fig-cap: Impact of the weekday-weekend difference on delay times

fig = px.box(
  df, x='Min Delay', y='Weekend', log_x=True,
  labels={'Min Delay' : 'Delay Length (in Minutes)'}, 
  title='Distribution of Delay Durations on Weekdays and Weekends'
)

fig.update_traces(
  hovertemplate=(
    'Delay Length: %{x} minutes <br>' +
    'Weekend: %{y} <extra></extra>'
  )
)

fig.show()
```

## Modelling
### Grid Search

We tune the following four hyperparameters for random forest, based on the information shown in the scikit-learn random forest [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html): max_features (number of feature tested per tree), n_estimators (number of trees to fit), min_samples_split (number of samples in an internal node necessary to split that node), and min_samples_leaf (number of samples required in each leaf). The tested values and the optimal combination are presented below:

```{python}
#| label: tbl-rf-hyperparams
#| tbl-cap: Optimal hyperparameter values for random forest

rf_table = [
  ['max_features', 'sqrt, 1/3, 1/2', '1/3'],
  ['n_estimators', '100, 200, 500', '200'],
  ['min_samples_split', '50, 100, 200', '50'],
  ['min_samples_leaf', '1, 5, 10', '1']
]

Markdown(tabulate(
  rf_table, 
  headers=[
    'Hyperparameter', 'Values Tested', 'Optimal Value'
  ]
))
```

```{python}
rfr = RandomForestRegressor(
  max_features=1/2,
  n_estimators=500,
  min_samples_split=100,
  min_samples_leaf=1,
  oob_score=True,
  random_state=11
)

rfr.fit(X_train, y_train)
y_pred_rf = rfr.predict(X_test)
```

We tune the following four XGBoost hyperparameters: n_estimators (number of trees to fit), max_depth (maximum depth per tree), learning_rate (rate of shrinkage between trees), and reg_alpha (LASSO regularization rate). Further information related to these hyperparameters (and other ones) can be viewed at the XGBoost [documentation](https://xgboost.readthedocs.io/en/stable/parameter.html). 

```{python}
#| label: tbl-xgb-hyperparams
#| tbl-cap: Optimal hyperparameter values for XGBoost

xgb_table = [
  ['n_estimators', '100, 200, 500', '100'],
  ['max_depth', '3, 5, 7', '7'],
  ['learning_rate', '0.1, 1, 2', '0.1'],
  ['reg_alpha', '0, 0.2, 1', '1']
]

Markdown(tabulate(
  xgb_table, 
  headers=[
    'Hyperparameter', 'Values Tested', 'Optimal Value'
  ]
))
```

```{python}
# See https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.sklearn

xgb_mod = XGBRegressor(
  n_estimators=100,
  max_depth=3,
  learning_rate=0.1,
  reg_alpha=1,
  random_state=11
)

xgb_mod.fit(X_train, y_train)
y_pred_xgb = xgb_mod.predict(X_test)
```

### Model Comparison

We note that the random forest model performed much better across all three model-evaluation metrics. Specifically, the random forest $R^2$ of 0.2189 is significantly better than the XGBoost $R^2$ of 0.1328.

However, although the random forest model is better at capturing the variation of the delay times than the XGBoost model, the fact that the former model only attained an $R^2$ of around 0.22 implies that even the random forest model may not be able to detect many pattern in the delay lengths (assuming that statistically-significant patterns exist in the first place).

We also observe that the random forest model had both a lower RMSE and a lower MAE than the XGBoost model. In particular, although the random forest RMSE of 7.76 minutes is large when compared to the fact that the mean delay duration is 7.22 minutes, we also note that there are many longer delays (some over one hour) that we keep in the dataset. In this context, we could conclude that both models (but especially the random forest model) are able to give decent predictions even in case of longer delays.

In addition, we note that the MAE is 3.92 minutes for random forest and 4.12 minutes for XGBoost. Given that MAE is more resilient to outliers (in this case, long delays) and that our dataset is right-skewed in favour of shorter delays, the relatively low MAEs imply that in general (i.e. excluding outliers), both models would give errors that are relatively large when compared to (for example) the mean delay duration of 7.22 minutes or the median delay duration of five minutes.

However, given the linear nature of delay times (i.e. a four-minute error in the predictions would be equally problematic for a true delay duration of any length), we can conclude that the MAE paints a more realistic picture of model performance given its resilience to outlier delay durations.

```{python}
#| label: tbl-best-performance
#| tbl-cap: Test performance for both models given the optimal hyperparameter values above

rf_rmse = root_mean_squared_error(y_test, y_pred_rf)
xgb_rmse = root_mean_squared_error(y_test, y_pred_xgb)

best_performance = [
  [
    'R^2', 
    np.round(r2_score(y_test, y_pred_rf), 4),
    np.round(r2_score(y_test, y_pred_xgb), 4)
  ],
  [
    'RMSE (in minutes)',
    np.round(rf_rmse, 4),
    np.round(xgb_rmse, 4)
  ],
  [
    # See https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html
    'MAE (in minutes)',
    np.round(mean_absolute_error(y_test, y_pred_rf), 4),
    np.round(mean_absolute_error(y_test, y_pred_xgb), 4)
  ]
]

Markdown(
  tabulate(best_performance, headers=[
    'Metric', 'Random Forest Value', 'XGBoost Value'
  ])
)
```

We choose the random forest model since it performed better across all of the three pre-determined metrics: $R^2$, RMSE, and MAE.

### Feature Importance and Interpretation

The following is a feature importance plot, identifying the most influential features with respect to the random forest model fitted above.

```{python}
# See Week 8 Slide 54 (https://jsc370.github.io/JSC370-2026/slides/08-ml2/JSC370-slides-08.html#/xgboost-variable-importance) and https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html
rf_imp_df = pd.DataFrame(
  rfr.feature_importances_,
  columns=['Importance'],
  index=X_train.columns
).reset_index(names='Feature')

# Cast as categorical type
rf_imp_df.Feature = rf_imp_df.Feature.astype('category')

# Add delay code meaning
delay_meaning_bis = delay_meaning.copy()
delay_meaning_bis.Code = delay_meaning.Code.apply(
  lambda x: 'Code_' + x # Use feature names (e.g. "Code_MUPLB") instead
)

# Merge code meaning with feature importance
rf_imp_df = rf_imp_df.merge(
  delay_meaning_bis, how='left', left_on='Feature', right_on='Code'
)

rf_imp_df.drop(['Code'], axis=1, inplace=True)
rf_imp_df.Meaning = rf_imp_df.Meaning.fillna('N/A')

# Sort by importance in descending order
rf_imp_df.sort_values(['Importance'], ascending=False, inplace=True)
```

```{python}
#| label: fig-feature-importance
#| fig-cap: Feature importance for the random forest model

fig = px.bar(
  rf_imp_df.head(20), 
  x='Feature',
  y='Importance',
  custom_data=['Meaning'],
  title='Twenty Most Important Features in the Random Forest Model'
)

fig.update_traces(
  hovertemplate=(
    'Feature: %{x} <br>' +
    'Importance: %{y:.4f} <br>' + 
    'Code Meaning: %{customdata[0]} <extra></extra>'
  )
)

fig.show()
```

14 features (exactly 70%) of the twenty most important features are delay codes. Many of those error codes pertain to infrastructure issues: for instance, problems with track switches or the third rail (which powers subway trains) are both important predictors of delay lengths. In particular, those delay causes could be mitigated with TTC maintenance.

On the other hand, several important predictors of delay lengths lie outside of the TTC's control, such as delays caused by people jumping (or being pushed) down to track level, or ill passengers being transported away for treatment.

Regardless of whether the exact cause of delay pertains to TTC maintenance, we can still conclude that background factors (e.g. weather, geography, or ridership) are less important than the cause of the error itself when predicting the error lengths.

Nonetheless, several important predictors of delay lengths are unrelated to causes of delays; some such features pertain to the weather (e.g. temperature and humidity) or geography (e.g. crow-flies distance from Union Station). This implies that factors related to weather and geography still have a non-negligible effect on the delay durations.

In addition, although the hypothesis tests above established that the subway line (1, 2, or 4) and the weekday-weekend difference are individually statistically significant predictors of delay length, neither feature made it to the twenty-most important features shown above.

Taking the two pieces of evidence (the tests and the plot) together, we may conclude that the impact that either feature (individually) exerts on the delay duration is statistically significant (per the test) but not important (per the plot). In other words, the influence is most likely there, but not as important as the influence exerted by the delay codes (for example).

Finally, we note that the hypothesis tests examined the line and the weekday-weekend difference in isolation, whereas the random forest model (and, by extension, the feature importance plot) examined every feature simultaneously. This may be the cause of the tests and the plot providing different insights.

# Conclusion
## Summary of Insights

Through various statistical methods, including hypothesis testing and modelling (random forest and XGBoost), we are able to discover some key predictors of subway delay lengths.

From the feature-importance plot above, we learnt that the several delay codes are important predictors of subway delay length. In particular, some causes of delays that significantly influence delay durations relate to potentially life-threatening conditions, including passengers requiring medical attention or intruders on tracks.

As important as they are in determining the delay lengths, those causes of delays are, unfortunately, mostly out of the TTC's (or commuters') control. However, some infrastructure upgrades, such as platform screen doors (which prevent passengers from accessing the track level), may help counteract the effects of some such causes of delays.

Nonetheless, some of the most important predictors of delay lengths still relate to TTC infrastructure. For instance, issues with track switches and the third rail (which powers trains) are within the five most important determiners of delay length. Since TTC maintenance could still mitigate those causes of delays, this implies that the TTC could (and should) enhance their maintenance regimen to minimize the chance of such an infrastructure-related delay.

With respect to features unrelated to the causes (codes) of the delays, we note that the weather, specifically temperature and humidity, has a somewhat significant influence on delay times, though not to the extent of the delays' causes. Without discounting the importance of weather-proofing the TTC via infrastructure maintenance and upgrades, this insight shows that weather-related issues need not be at the forefront of TTC infrastructure-improvement programs (or the commuters' trip-planning).

In addition, we observe that geography, for the most part, does not significantly influence delay lengths. However, we note that the (crow-flies) distance from Union Station and ridership are both within the twenty most important features. This suggests that there still exists a difference between the delay lengths of downtown and suburban subway stations, perhaps (but not necessarily) due to ridership differences between the two types of stations.

Finally, we note that ridership remain an important feature to the random forest model despite the t-test ruling out a statistically-significant association between delay length and station ridership. This may be due to the fact that ridership is tested in isolation within the t-test, whereas it is tested as one of many features within the random forest model.

## Stakeholder Impact

Commuters could now be more mindful of the fact that long delays could also result from factors beyond the TTC's control, such as ill passengers. In addition, this analysis could remind them of the importance of subway infrastructure remaining in good condition.

This analysis could help commuters appreciate the need for the subway to remain in good shape, while educating them as to the necessity of track work (e.g. scheduled weekend closures) and adequate funding in upholding excellent infrastruction conditions and consequently reducing the length of subway delays. This would hopefully help Torontonians lobby for greater funding and resource allocations to the TTC's day-to-day maintenance work.

On the other hand, the TTC could now prioritize keeping subway infrastructure in good condition in order to reduce the duration (and also the frequency) of infrastructure-related subway delays. This analysis has shown that infrastructure-related issues (e.g. switch or third-rail problems) have some of the strongest influences on delay lengths; this could hopefully show the TTC the importance of securing funding and other resources to enhance their maintenance of subway infrastructure so as to reduce subway delay durations (and frequency) in the interest of Torontonians.

## Limitations

The Open Data dataset only contains data involving delays *at a specific station* (e.g. trained stalled at a station due to medical problem). Although some issues (such as trespassers at the track level) would necessitate the closure of a stretch of subway, these delays would not have been recorded in the API. This means that our analysis does not take subway closures (scheduled or not) into account.

In addition, as noted above, the random forest model has a $R^2$ value of only around 0.22, implying that it failed to capture much of the variation in delay durations. This may simply be because of the nature of the data itself (i.e. the delay durations could be relatively independent of the features in the dataset), but more statistical  investigations into the model and the data itself would be required to identify the cause of the low $R^2$.

Finally, we note that the delay times remain very right-skewed notwithstanding our removal of problematic delay times. Although we must keep some long delays in our datasets to ensure we could predict longer delays, we also note that the training data is heavily skewed in favour of short delays, affecting its ability to predict longer delays.

In the future, transformations (both of the features and of the delay durations) could be incorporated into the analysis in order to mitigate the effect of skewed features or delay durations on model performance.